<?php

return [
    'exchange_rate_api_key' => env('EXCHANGE_RATE_API_KEY'),
    'currencies' => [
        'DZD' => [
            'name' => 'Algerian Dinar',
            'symbol' => 'DA',
            'code' => 'DZD',
            'country' => 'Algeria',
            'exchange_rate_to_usd' => null,
        ],
        'AOA' => [
            'name' => 'Angolan Kwanza',
            'symbol' => 'Kz',
            'code' => 'AOA',
            'country' => 'Angola',
            'exchange_rate_to_usd' => null,
        ],
        'XOF' => [
            'name' => 'West African CFA franc',
            'symbol' => 'CFA',
            'code' => 'XOF',
            'country' => 'Benin, Burkina Faso, Côte d\'Ivoire, Guinea-Bissau, Mali, Niger, Senegal, Togo',
            'exchange_rate_to_usd' => null,
        ],
        'BWP' => [
            'name' => 'Botswana Pula',
            'symbol' => 'P',
            'code' => 'BWP',
            'country' => 'Botswana',
            'exchange_rate_to_usd' => null,
        ],
        'BIF' => [
            'name' => 'Burundi Franc',
            'symbol' => 'FBu',
            'code' => 'BIF',
            'country' => 'Burundi',
            'exchange_rate_to_usd' => null,
        ],
        'CVE' => [
            'name' => 'Cabo Verde Escudo',
            'symbol' => '$',
            'code' => 'CVE',
            'country' => 'Cabo Verde',
            'exchange_rate_to_usd' => null,
        ],
        'XAF' => [
            'name' => 'Central African CFA franc',
            'symbol' => 'FCFA',
            'code' => 'XAF',
            'country' => 'Cameroon, Central African Republic, Chad, Congo (Republic), Equatorial Guinea, Gabon',
            'exchange_rate_to_usd' => null,
        ],
        'KMF' => [
            'name' => 'Comorian Franc',
            'symbol' => 'CF',
            'code' => 'KMF',
            'country' => 'Comoros',
            'exchange_rate_to_usd' => null,
        ],
        'CDF' => [
            'name' => 'Congolese Franc',
            'symbol' => 'FC',
            'code' => 'CDF',
            'country' => 'Democratic Republic of Congo',
            'exchange_rate_to_usd' => null,
        ],
        'DJF' => [
            'name' => 'Djiboutian Franc',
            'symbol' => 'Fdj',
            'code' => 'DJF',
            'country' => 'Djibouti',
            'exchange_rate_to_usd' => null,
        ],
        'EGP' => [
            'name' => 'Egyptian Pound',
            'symbol' => 'E£',
            'code' => 'EGP',
            'country' => 'Egypt',
            'exchange_rate_to_usd' => null,
        ],
        'ERN' => [
            'name' => 'Eritrean Nakfa',
            'symbol' => 'Nfk',
            'code' => 'ERN',
            'country' => 'Eritrea',
            'exchange_rate_to_usd' => null,
        ],
        'SZL' => [
            'name' => 'Swazi Lilangeni',
            'symbol' => 'E',
            'code' => 'SZL',
            'country' => 'Eswatini',
            'exchange_rate_to_usd' => null,
        ],
        'ETB' => [
            'name' => 'Ethiopian Birr',
            'symbol' => 'Br',
            'code' => 'ETB',
            'country' => 'Ethiopia',
            'exchange_rate_to_usd' => null,
        ],
        'GMD' => [
            'name' => 'Gambian Dalasi',
            'symbol' => 'D',
            'code' => 'GMD',
            'country' => 'Gambia',
            'exchange_rate_to_usd' => null,
        ],
        'GHS' => [
            'name' => 'Ghanaian Cedi',
            'symbol' => 'GH₵',
            'code' => 'GHS',
            'country' => 'Ghana',
            'exchange_rate_to_usd' => null,
        ],
        'GNF' => [
            'name' => 'Guinean Franc',
            'symbol' => 'FG',
            'code' => 'GNF',
            'country' => 'Guinea',
            'exchange_rate_to_usd' => null,
        ],
        'KES' => [
            'name' => 'Kenyan Shilling',
            'symbol' => 'KSh',
            'code' => 'KES',
            'country' => 'Kenya',
            'exchange_rate_to_usd' => null,
        ],
        'LSL' => [
            'name' => 'Lesotho Loti',
            'symbol' => 'L',
            'code' => 'LSL',
            'country' => 'Lesotho',
            'exchange_rate_to_usd' => null,
        ],
        'LRD' => [
            'name' => 'Liberian Dollar',
            'symbol' => '$',
            'code' => 'LRD',
            'country' => 'Liberia',
            'exchange_rate_to_usd' => null,
        ],
        'LYD' => [
            'name' => 'Libyan Dinar',
            'symbol' => 'LD',
            'code' => 'LYD',
            'country' => 'Libya',
            'exchange_rate_to_usd' => null,
        ],
        'MGA' => [
            'name' => 'Malagasy Ariary',
            'symbol' => 'Ar',
            'code' => 'MGA',
            'country' => 'Madagascar',
            'exchange_rate_to_usd' => null,
        ],
        'MWK' => [
            'name' => 'Malawian Kwacha',
            'symbol' => 'MK',
            'code' => 'MWK',
            'country' => 'Malawi',
            'exchange_rate_to_usd' => null,
        ],
        'MRU' => [
            'name' => 'Mauritanian Ouguiya',
            'symbol' => 'UM',
            'code' => 'MRU',
            'country' => 'Mauritania',
            'exchange_rate_to_usd' => null,
        ],
        'MUR' => [
            'name' => 'Mauritian Rupee',
            'symbol' => 'Rs',
            'code' => 'MUR',
            'country' => 'Mauritius',
            'exchange_rate_to_usd' => null,
        ],
        'MAD' => [
            'name' => 'Moroccan Dirham',
            'symbol' => 'DH',
            'code' => 'MAD',
            'country' => 'Morocco',
            'exchange_rate_to_usd' => null,
        ],
        'MZN' => [
            'name' => 'Mozambican Metical',
            'symbol' => 'MT',
            'code' => 'MZN',
            'country' => 'Mozambique',
            'exchange_rate_to_usd' => null,
        ],
        'NAD' => [
            'name' => 'Namibian Dollar',
            'symbol' => '$',
            'code' => 'NAD',
            'country' => 'Namibia',
            'exchange_rate_to_usd' => null,
        ],
        'NGN' => [
            'name' => 'Nigerian Naira',
            'symbol' => '₦',
            'code' => 'NGN',
            'country' => 'Nigeria',
            'exchange_rate_to_usd' => null,
        ],
        'RWF' => [
            'name' => 'Rwandan Franc',
            'symbol' => 'RF',
            'code' => 'RWF',
            'country' => 'Rwanda',
            'exchange_rate_to_usd' => null,
        ],
        'STN' => [
            'name' => 'Sao Tome and Principe Dobra',
            'symbol' => 'Db',
            'code' => 'STN',
            'country' => 'Sao Tome and Principe',
            'exchange_rate_to_usd' => null,
        ],
        'SCR' => [
            'name' => 'Seychellois Rupee',
            'symbol' => 'Rs',
            'code' => 'SCR',
            'country' => 'Seychelles',
            'exchange_rate_to_usd' => null,
        ],
        'SLE' => [
            'name' => 'Sierra Leonean Leone',
            'symbol' => 'Le',
            'code' => 'SLE',
            'country' => 'Sierra Leone',
            'exchange_rate_to_usd' => null,
        ],
        'SOS' => [
            'name' => 'Somali Shilling',
            'symbol' => 'Sh.So.',
            'code' => 'SOS',
            'country' => 'Somalia',
            'exchange_rate_to_usd' => null,
        ],
        'ZAR' => [
            'name' => 'South African Rand',
            'symbol' => 'R',
            'code' => 'ZAR',
            'country' => 'South Africa',
            'exchange_rate_to_usd' => null,
        ],
        'SSP' => [
            'name' => 'South Sudanese Pound',
            'symbol' => '£',
            'code' => 'SSP',
            'country' => 'South Sudan',
            'exchange_rate_to_usd' => null,
        ],
        'SDG' => [
            'name' => 'Sudanese Pound',
            'symbol' => '£Sd',
            'code' => 'SDG',
            'country' => 'Sudan',
            'exchange_rate_to_usd' => null,
        ],
        'TZS' => [
            'name' => 'Tanzanian Shilling',
            'symbol' => 'TSh',
            'code' => 'TZS',
            'country' => 'Tanzania',
            'exchange_rate_to_usd' => null,
        ],
        'TND' => [
            'name' => 'Tunisian Dinar',
            'symbol' => 'DT',
            'code' => 'TND',
            'country' => 'Tunisia',
            'exchange_rate_to_usd' => null,
        ],
        'UGX' => [
            'name' => 'Ugandan Shilling',
            'symbol' => 'USh',
            'code' => 'UGX',
            'country' => 'Uganda',
            'exchange_rate_to_usd' => null,
        ],
        'ZMW' => [
            'name' => 'Zambian Kwacha',
            'symbol' => 'K',
            'code' => 'ZMW',
            'country' => 'Zambia',
            'exchange_rate_to_usd' => null,
        ],
        'ZWL' => [
            'name' => 'Zimbabwean Dollar',
            'symbol' => 'Z$',
            'code' => 'ZWL',
            'country' => 'Zimbabwe',
            'exchange_rate_to_usd' => null,
        ],
    ],
];